/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class AddService extends javax.swing.JFrame {

    /**
     * Creates new form AddService
     */
    public AddService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Service");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Name", "Category", "Quantity", "Price", "Time Added", "Expiration Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String username = "root";
    String password = ""; 
    java.sql.Connection conn = null;

    try {
        // Kết nối cơ sở dữ liệu
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nmcnpm_btl", username, password);

        // Duyệt qua tất cả các hàng trong bảng
        int rowCount = jTable1.getRowCount(); // Số lượng hàng trong bảng
        System.out.println("Row count: " + rowCount);  // In ra số hàng để kiểm tra

        for (int i = 0; i < rowCount; i++) {
            // Kiểm tra dữ liệu của các ô trong bảng
            String id_name = (String) jTable1.getValueAt(i, 0);
            String cate = (String) jTable1.getValueAt(i, 1);
            Object quantityObj = jTable1.getValueAt(i, 2);
            Object priceObj = jTable1.getValueAt(i, 3);
            String time_added_str = (String) jTable1.getValueAt(i, 4);
            String exp_date_str = (String) jTable1.getValueAt(i, 5);

            // Kiểm tra null hoặc chuỗi rỗng cho từng giá trị
            if (id_name == null || id_name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Name cannot be empty or null!");
                return;  // Dừng lại nếu giá trị là null hoặc rỗng
            }

            if (cate == null || cate.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Category cannot be empty or null!");
                return;  // Dừng lại nếu giá trị là null hoặc rỗng
            }

            int quantity = 0;
            if (quantityObj != null) {
                quantity = (int) quantityObj;
            } else {
                JOptionPane.showMessageDialog(this, "Quantity cannot be null!");
                return;  // Dừng lại nếu không có giá trị hợp lệ
            }

            float price = 0;
            if (priceObj != null) {
                price = ((Number) priceObj).floatValue();
            } else {
                JOptionPane.showMessageDialog(this, "Price cannot be null!");
                return;  // Dừng lại nếu không có giá trị hợp lệ
            }

            // Loại bỏ dấu cách trước và sau chuỗi
            time_added_str = time_added_str != null ? time_added_str.trim() : "";
            exp_date_str = exp_date_str != null ? exp_date_str.trim() : "";

            // Kiểm tra nếu các cột ngày tháng là rỗng
            if (time_added_str.isEmpty() || exp_date_str.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Date fields cannot be empty or null!");
                return;  // Dừng lại nếu không có giá trị hợp lệ
            }

            // Chuyển chuỗi ngày tháng thành đối tượng Date
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            Date time_added = null;
            Date exp_date = null;

            try {
                time_added = sdf.parse(time_added_str);  // Chuyển đổi String thành Date
                // Kiểm tra nếu ngày hết hạn là null hoặc không có dữ liệu hợp lệ
                if (!exp_date_str.isEmpty()) {
                    exp_date = sdf.parse(exp_date_str);  // Chuyển đổi String thành Date
                }
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Invalid date format. Please use yyyy-MM-dd.");
                return;  // Dừng lại nếu lỗi định dạng ngày tháng
            }

            // Câu truy vấn SQL để thêm dữ liệu vào bảng Inventory
            String query1 = "INSERT INTO Inventory (item_name, category, quantity, price, added_at, expire_date) VALUES (?,?,?,?,?,?);";
            PreparedStatement statement = conn.prepareStatement(query1);

            // Gán giá trị vào PreparedStatement
            statement.setString(1, id_name);
            statement.setString(2, cate);
            statement.setInt(3, quantity);
            statement.setFloat(4, price);
            statement.setTimestamp(5, new java.sql.Timestamp(time_added.getTime()));  // Chuyển Date sang java.sql.Timestamp
            if (exp_date != null) {
                statement.setTimestamp(6, new java.sql.Timestamp(exp_date.getTime()));    // Chuyển Date sang java.sql.Timestamp
            } else {
                statement.setNull(6, java.sql.Types.TIMESTAMP); // Nếu không có ngày hết hạn, đặt giá trị NULL
            }

            // Thực thi câu lệnh INSERT
            int rowsAffected = statement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Added Successfully!");
            }
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error while adding record: " + ex.getMessage());
    } catch (ClassNotFoundException ex) {
        ex.printStackTrace();
        Logger.getLogger(AddService.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    } finally {
        // Đảm bảo đóng kết nối
        try {
            if (conn != null && !conn.isClosed()) {
                conn.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
